name: Update Activity Graph

on:

  schedule:

    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - name: Done

        run: echo "Activity Graph Updated"
